// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySkiStats.Api.Data;

#nullable disable

namespace MySkiStats.Api.Migrations
{
    [DbContext(typeof(SkiStatsContext))]
    [Migration("20260122123528_ActivityModelChange")]
    partial class ActivityModelChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("MySkiStats.Api.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ascent")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AthleteGearId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AthleteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Descent")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Distance")
                        .HasColumnType("REAL");

                    b.Property<double>("ElapsedTime")
                        .HasColumnType("REAL");

                    b.Property<double>("Grade")
                        .HasColumnType("REAL");

                    b.Property<double>("MovingTime")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Runs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StravaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActivityTypeId");

                    b.HasIndex("AthleteGearId");

                    b.HasIndex("AthleteId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("MySkiStats.Api.Models.ActivityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ActivityTypes");
                });

            modelBuilder.Entity("MySkiStats.Api.Models.Athlete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("StravaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Athletes");
                });

            modelBuilder.Entity("MySkiStats.Api.Models.AthleteGear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AthleteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BuyDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("GearTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("GearTypeId");

                    b.ToTable("AthleteGears");
                });

            modelBuilder.Entity("MySkiStats.Api.Models.GearType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GearTypes");
                });

            modelBuilder.Entity("MySkiStats.Api.Models.Activity", b =>
                {
                    b.HasOne("MySkiStats.Api.Models.ActivityType", "ActivityType")
                        .WithMany("Activities")
                        .HasForeignKey("ActivityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MySkiStats.Api.Models.AthleteGear", "AthleteGear")
                        .WithMany("Activities")
                        .HasForeignKey("AthleteGearId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MySkiStats.Api.Models.Athlete", "Athlete")
                        .WithMany("Activities")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityType");

                    b.Navigation("Athlete");

                    b.Navigation("AthleteGear");
                });

            modelBuilder.Entity("MySkiStats.Api.Models.AthleteGear", b =>
                {
                    b.HasOne("MySkiStats.Api.Models.Athlete", "Athlete")
                        .WithMany("Gears")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySkiStats.Api.Models.GearType", "GearType")
                        .WithMany("Gears")
                        .HasForeignKey("GearTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("GearType");
                });

            modelBuilder.Entity("MySkiStats.Api.Models.ActivityType", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("MySkiStats.Api.Models.Athlete", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Gears");
                });

            modelBuilder.Entity("MySkiStats.Api.Models.AthleteGear", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("MySkiStats.Api.Models.GearType", b =>
                {
                    b.Navigation("Gears");
                });
#pragma warning restore 612, 618
        }
    }
}
